language: java

install:
    - git clone https://github.com/openworm/org.geppetto.model.git -b development
    - cd org.geppetto.model
    - git checkout $TRAVIS_BRANCH
    - mvn install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.core.git -b development
    - cd org.geppetto.core
    - git checkout $TRAVIS_BRANCH
    - mvn install
    - cd ..    
    - git clone https://github.com/openworm/org.geppetto.simulation.git -b development
    - cd org.geppetto.simulation
    - git checkout $TRAVIS_BRANCH
    - mvn install
    - cd ..    
matrix:
  allow_failures:
    - install: git checkout $TRAVIS_BRANCH
    
    
    
 
 


